# Config file for automatic testing at travis-ci.org
language: python

python:
  - "2.7"

# Anaconda information comes from https://gist.github.com/dan-blanchard/7045057
# Setup anaconda
before_install:
  # Uses latest version of Miniconda2 or 3 respectively now
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget http://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
# Install packages
install:
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
  - conda install -n test-environment pip
  - conda install -n test-environment atlas numpy scipy matplotlib h5py nose beautiful-soup docutils pystan seaborn statsmodels
  - source activate test-environment
  - pip install pint uncertainties click bunch
  - python setup.py install
 
# Run test
script:
  - nosetests